# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fetch < Formula
  desc ""
  homepage "https://github.com/wklken/homebrew-fetch"
  version "1.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wklken/fetch/releases/download/v1.0.7/fetch_1.0.7_darwin_amd64.tar.gz"
      sha256 "bcd4a7c90401fdf22f5bda7d6e1b26fa1ad131f8deb479067af8c110fa93b88c"

      def install
        bin.install "fetch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wklken/fetch/releases/download/v1.0.7/fetch_1.0.7_darwin_arm64.tar.gz"
      sha256 "f30f0028176633a120ca52e7b8c7a984ec9cd303af3f3e00f8d29f39fd1fa62e"

      def install
        bin.install "fetch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wklken/fetch/releases/download/v1.0.7/fetch_1.0.7_linux_arm64.tar.gz"
      sha256 "021de64de09cfb19af1956ae42948d0d57d547a36946b2514ee16584cefe356e"

      def install
        bin.install "fetch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wklken/fetch/releases/download/v1.0.7/fetch_1.0.7_linux_amd64.tar.gz"
      sha256 "4addd333b33d77efe9d013330f3272cb97d11db72412c317dd9bb58e52ffad7a"

      def install
        bin.install "fetch"
      end
    end
  end
end
