# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fetch < Formula
  desc ""
  homepage "https://github.com/wklken/homebrew-fetch"
  version "1.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wklken/fetch/releases/download/v1.0.8/fetch_1.0.8_darwin_amd64.tar.gz"
      sha256 "484e571d0227da53fa7e774ddb275f816d3b64b9533846ce7e9e522a69197da8"

      def install
        bin.install "fetch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wklken/fetch/releases/download/v1.0.8/fetch_1.0.8_darwin_arm64.tar.gz"
      sha256 "0faf2fe71ce4f226f74ecc31f525619fd8a42ac2ed1020d943b777480ec42f89"

      def install
        bin.install "fetch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wklken/fetch/releases/download/v1.0.8/fetch_1.0.8_linux_amd64.tar.gz"
      sha256 "388257540459144d1e4d6612f14b949ba167f8a5541e81d774ad94f5ac983372"

      def install
        bin.install "fetch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wklken/fetch/releases/download/v1.0.8/fetch_1.0.8_linux_arm64.tar.gz"
      sha256 "fbacfe046a0580ccb71ce84487cf7ec14c011af827fc218ea6695a8b9d36a1d3"

      def install
        bin.install "fetch"
      end
    end
  end
end
