# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Httptest < Formula
  desc ""
  homepage "https://github.com/wklken/homebrew-httptest"
  version "1.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wklken/httptest/releases/download/v1.0.5/httptest_1.0.5_darwin_amd64.tar.gz"
      sha256 "1b093b8f2fae547f1def7ddeb4c5d62ebe0a6a58272b577bbc3223228aa2689d"

      def install
        bin.install "httptest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wklken/httptest/releases/download/v1.0.5/httptest_1.0.5_darwin_arm64.tar.gz"
      sha256 "029c9b68168f123b5ea0d82b943a0e0bbc7b78270fc4e8dda51112ae2f25001c"

      def install
        bin.install "httptest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wklken/httptest/releases/download/v1.0.5/httptest_1.0.5_linux_arm64.tar.gz"
      sha256 "975e94b48b76413728e03be08ebc3406fa041c46ab43b6fb0699572b782161c9"

      def install
        bin.install "httptest"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wklken/httptest/releases/download/v1.0.5/httptest_1.0.5_linux_amd64.tar.gz"
      sha256 "0b78f368a597e1d7c47e5bf59eb6c59233bb600654080fffab75f826c7527035"

      def install
        bin.install "httptest"
      end
    end
  end
end
